import { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  MemoryStick, Grid3X3, Layers, 
  CheckCircle, Search, Cpu, Shield,
  Terminal
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 }
};

export default function Chapter8() {
  const [pageSize, setPageSize] = useState(4);
  const [logicalAddress, setLogicalAddress] = useState(13);

  // Calculate physical address
  const page = Math.floor(logicalAddress / pageSize);
  const offset = logicalAddress % pageSize;
  const pageTable = [5, 1, 2, 8];
  const frame = pageTable[page] || 0;
  const physicalAddress = frame * pageSize + offset;

  return (
    <div className="space-y-8">
      {/* Header */}
      <motion.div {...fadeIn} className="text-center space-y-4">
        <Badge variant="secondary" className="text-sm">Chapter 8</Badge>
        <h1 className="text-4xl font-bold text-gray-900">Main Memory</h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Comprehensive deep dive into memory management, address translation, paging, segmentation, and real-world backend applications
        </p>
      </motion.div>

      {/* Background and Address Spaces */}
      <motion.div {...fadeIn}>
        <Card className="border-l-4 border-l-gray-500">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <MemoryStick className="w-6 h-6 text-gray-500" />
              Background: Logical vs Physical Address Space
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="bg-gray-50 p-5 rounded-lg">
              <p className="text-gray-800 text-lg leading-relaxed">
                Memory management is one of the most critical functions of an operating system. 
                The CPU can only directly access memory and processor-built-in registers. 
                Therefore, instructions and data must be in main memory to be processed.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Cpu className="w-5 h-5" />
                  Logical (Virtual) Address
                </h4>
                <p className="text-sm text-gray-700 mb-2">
                  Generated by the CPU. Also called virtual address. The set of all logical addresses 
                  generated by a program constitutes the logical address space.
                </p>
                <ul className="text-sm text-gray-700 space-y-1">
                  <li>• Generated during program execution</li>
                  <li>• Independent of physical memory layout</li>
                  <li>• Starts at address 0 for every process</li>
                  <li>• Must be translated to physical addresses</li>
                </ul>
              </div>

              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Grid3X3 className="w-5 h-5" />
                  Physical Address
                </h4>
                <p className="text-sm text-gray-700 mb-2">
                  The actual address seen by the memory unit. The set of all physical addresses 
                  corresponds to the physical address space.
                </p>
                <ul className="text-sm text-gray-700 space-y-1">
                  <li>• Actual location in RAM hardware</li>
                  <li>• Unique across the entire system</li>
                  <li>• Managed by the OS and MMU</li>
                  <li>• Processes cannot directly access</li>
                </ul>
              </div>
            </div>

            <div className="bg-slate-900 p-5 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">Address Binding Timeline</h4>
              <pre className="text-gray-300 text-xs md:text-sm font-mono">
{`
Compile Time          Load Time             Execution Time
   |                      |                       |
   v                      v                       v
+--------+           +--------+             +--------+
| Symbol | --bind-> | Reloc. | --bind-->   | MMU    |
| Addr   |           | Addr   |               | Dynamic|
+--------+           +--------+             +--------+
   |                      |                       |
Fixed address        Can be relocated      Most flexible
Absolute code        at load time          (modern systems)
`}
              </pre>
            </div>

            <div className="bg-slate-100 p-5 rounded-lg">
              <h4 className="font-semibold mb-4">Memory Management Unit (MMU) in Detail</h4>
              <p className="text-sm text-gray-700 mb-3">
                The MMU is a hardware device that maps virtual addresses to physical addresses. 
                In the simplest scheme, the value in the relocation register is added to every 
                address generated by a user process at the time it is sent to memory.
              </p>
              <div className="grid md:grid-cols-2 gap-4">
                <div className="bg-white p-4 rounded border-l-4 border-gray-400">
                  <h5 className="font-semibold text-gray-900">Base (Relocation) Register</h5>
                  <p className="text-sm text-gray-600 mt-1">
                    Contains the starting physical address of the process. 
                    Every logical address is added to the base register.
                  </p>
                  <p className="text-xs text-gray-500 mt-2 font-mono">
                    physical_address = logical_address + base_register
                  </p>
                </div>
                <div className="bg-white p-4 rounded border-l-4 border-gray-400">
                  <h5 className="font-semibold text-gray-900">Limit Register</h5>
                  <p className="text-sm text-gray-600 mt-1">
                    Contains the size of the logical address range. 
                    Any address greater than or equal to the limit generates a trap.
                  </p>
                  <p className="text-xs text-gray-500 mt-2 font-mono">
                    if (logical_address &gt;= limit) TRAP
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Memory Allocation Strategies */}
      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Layers className="w-6 h-6 text-gray-500" />
              Contiguous Memory Allocation and Fragmentation
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <p className="text-gray-700">
              In contiguous memory allocation, each process is contained in a single contiguous section of memory. 
              The OS maintains information about which parts of memory are allocated and which are free.
            </p>

            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Fixed Partitioning</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Memory is divided into fixed-size partitions. Each partition holds exactly one process.
                  Simple to implement but highly inefficient.
                </p>
                <div className="bg-white p-3 rounded border-l-4 border-gray-400 mt-3">
                  <p className="text-sm font-semibold text-gray-700">Internal Fragmentation</p>
                  <p className="text-xs text-gray-600 mt-1">
                    Waste occurs when a process is smaller than its allocated partition. 
                    The unused space inside the partition cannot be allocated to another process.
                  </p>
                </div>
              </div>

              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Dynamic Partitioning</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Partitions are created dynamically to fit the exact size of each process. 
                  More flexible but introduces a different problem.
                </p>
                <div className="bg-white p-3 rounded border-l-4 border-gray-400 mt-3">
                  <p className="text-sm font-semibold text-gray-700">External Fragmentation</p>
                  <p className="text-xs text-gray-600 mt-1">
                    Waste occurs when free memory is broken into small, non-contiguous pieces. 
                    Total free memory may be sufficient, but no single block is large enough.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-slate-900 p-5 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">External Fragmentation Visualization</h4>
              <pre className="text-gray-300 text-xs md:text-sm font-mono">
{`
Initial State:          After P1 and P3 exit:
+----------+            +----------+
|  P1 (2M) |            |  FREE    | <- 2M free
+----------+            +----------+
|  P2 (4M) |            |  P2 (4M) |
+----------+            +----------+
|  P3 (3M) |            |  FREE    | <- 3M free
+----------+            +----------+
|  P4 (5M) |            |  P4 (5M) |
+----------+            +----------+
|  FREE    |            |  FREE    | <- 4M free
|  (4M)    |            |  (4M)    |
+----------+            +----------+

Total free: 9M          Total free: 9M
Problem: Cannot fit P5 (6M) because no contiguous 6M block exists!
Solution: Compaction (shuffle memory to create one large free block)
`}
              </pre>
            </div>

            <div className="bg-gray-50 p-5 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-4">Dynamic Allocation Strategies Comparison</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-slate-200">
                      <th className="p-3 text-left">Strategy</th>
                      <th className="p-3 text-left">How It Works</th>
                      <th className="p-3 text-left">Time Complexity</th>
                      <th className="p-3 text-left">Fragmentation</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">First Fit</td>
                      <td className="p-3">Allocate first hole that is big enough</td>
                      <td className="p-3">O(n) search, fastest in practice</td>
                      <td className="p-3">Tends to fragment low addresses</td>
                    </tr>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Best Fit</td>
                      <td className="p-3">Allocate smallest adequate hole</td>
                      <td className="p-3">O(n) - must search entire list</td>
                      <td className="p-3">Leaves tiny unusable fragments</td>
                    </tr>
                    <tr className="bg-white">
                      <td className="p-3 font-medium">Worst Fit</td>
                      <td className="p-3">Allocate largest hole</td>
                      <td className="p-3">O(n) - must search entire list</td>
                      <td className="p-3">Leaves larger leftover pieces</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-slate-900 p-4 rounded-lg">
                <h4 className="text-gray-400 text-sm mb-2">First Fit Example</h4>
                <pre className="text-gray-300 text-xs font-mono">
{`
Holes: [10K, 30K, 5K, 20K]
Request: 15K

First Fit: Scan from start
  10K -> too small
  30K -> big enough! Allocate 15K
  Remaining: [10K, 15K, 5K, 20K]

Best Fit: Search all
  10K -> too small
  30K -> can fit
  5K  -> too small
  20K -> can fit (best!)
  Allocate 15K from 20K
  Remaining: [10K, 30K, 5K, 5K]

Worst Fit: Search all
  30K -> largest, allocate 15K
  Remaining: [10K, 15K, 5K, 20K]
`}
                </pre>
              </div>
              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-2">Mathematical Analysis</h4>
                <p className="text-sm text-gray-700 mb-3">
                  External fragmentation can be severe. Statistical analysis shows that given N allocated blocks, 
                  another 0.5N blocks may be lost to fragmentation. This means one-third of memory may be unusable.
                </p>
                <div className="bg-white p-3 rounded border-l-4 border-gray-400">
                  <p className="text-sm font-semibold text-gray-700">50-Percent Rule</p>
                  <p className="text-xs text-gray-600 mt-1">
                    On average, for every N allocated blocks, there are 0.5N fragments that cannot be used. 
                    Therefore, one-third of memory is lost to external fragmentation.
                  </p>
                </div>
                <p className="text-xs text-gray-600 mt-3">
                  Compaction (shuffling memory contents) solves external fragmentation but is expensive - 
                  O(n) where n is the total memory size, and I/O must be frozen during relocation.
                </p>
              </div>
            </div>

            <div className="bg-gray-50 p-5 rounded-lg border-l-4 border-gray-500">
              <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                <Terminal className="w-5 h-5" />
                Swapping and Compaction
              </h4>
              <p className="text-sm text-gray-700 mb-3">
                Swapping is a mechanism by which a process can be swapped temporarily out of main memory 
                to a backing store (disk), and brought back into memory for continued execution.
              </p>
              <div className="bg-slate-900 p-3 rounded text-gray-300 text-xs font-mono">
{`// Swapping overhead calculation
swap_time = transfer_size / disk_bandwidth
context_switch_time = 1-1000 microseconds
total_swap_out_time = swap_time + context_switch_time

// Example: Swapping 100MB to SSD at 500MB/s
swap_time = 100MB / 500MB/s = 200ms
// Major page fault is essentially a small swap operation`}
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Paging Deep Dive */}
      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Grid3X3 className="w-6 h-6 text-gray-500" />
              Paging: Architecture and Address Translation
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <p className="text-gray-700">
              Paging is a memory-management scheme that permits a process's physical address space to be noncontiguous. 
              It avoids the considerable problem of fitting variable-sized memory chunks onto the backing store.
            </p>

            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Core Concepts</h4>
                <ul className="text-sm text-gray-700 space-y-2">
                  <li>
                    <strong>Page:</strong> Fixed-size block in logical memory. 
                    Typical size: 4KB (2^12 bytes), 2MB (huge pages), 1GB.
                  </li>
                  <li>
                    <strong>Frame:</strong> Fixed-size block in physical memory. 
                    Frame size equals page size.
                  </li>
                  <li>
                    <strong>Page Table:</strong> Maps page numbers to frame numbers. 
                    One per process, stored in main memory.
                  </li>
                  <li>
                    <strong>Page Table Base Register (PTBR):</strong> Points to the page table 
                    of the currently running process.
                  </li>
                </ul>
              </div>

              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Address Structure</h4>
                <p className="text-sm text-gray-700 mb-2">
                  For a logical address space of 2^m bytes and page size of 2^n bytes:
                </p>
                <div className="bg-white p-3 rounded border border-gray-200">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="bg-gray-200 px-3 py-1 rounded text-xs font-mono">m-n bits</div>
                    <div className="bg-gray-300 px-3 py-1 rounded text-xs font-mono">n bits</div>
                  </div>
                  <p className="text-xs text-gray-600">Page Number | Page Offset</p>
                </div>
                <p className="text-xs text-gray-600 mt-2">
                  Example: 32-bit address, 4KB pages (2^12)
                  <br />
                  Page number: 20 bits (1,048,576 pages max)
                  <br />
                  Offset: 12 bits (0-4095 bytes within page)
                </p>
              </div>
            </div>

            <div className="bg-slate-900 p-5 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">Paging Hardware Architecture</h4>
              <pre className="text-gray-300 text-xs md:text-sm font-mono">
{`
     CPU generates                    MMU translates
     logical address                 to physical address
          |                                |
          v                                v
    +-----------+                    +------------+
    | Page Num  | --page table-->   | Frame Num  |
    |  (p)      |                    |   (f)      |
    +-----------+                    +------------+
    |  Offset   |                    |   Offset   |
    |   (d)     | <----------------- |    (d)     |
    +-----------+                    +------------+
          |                                |
          |         Page Table             |
          |      (in main memory)          |
          |    +------------------+        |
          +--->| Page 0 -> Frame 5|        |
               | Page 1 -> Frame 2|        |
               | Page 2 -> Frame 7|        |
               | ...              |        |
               +------------------+        |
                                           v
                                    Physical Memory
`}
              </pre>
            </div>

            {/* Interactive Paging Demo */}
            <Card className="bg-gray-50 border-l-4 border-l-gray-400">
              <CardContent className="p-5">
                <h4 className="font-semibold mb-4">Interactive: Address Translation Calculator</h4>
                
                <div className="flex flex-wrap gap-4 mb-4">
                  <div>
                    <label className="text-sm text-gray-600">Logical Address:</label>
                    <input 
                      type="number" 
                      value={logicalAddress}
                      onChange={(e) => setLogicalAddress(parseInt(e.target.value) || 0)}
                      className="ml-2 w-20 p-1 border border-gray-300 rounded bg-white"
                      min="0"
                      max="15"
                    />
                  </div>
                  <div>
                    <label className="text-sm text-gray-600">Page Size:</label>
                    <select 
                      value={pageSize}
                      onChange={(e) => setPageSize(parseInt(e.target.value))}
                      className="ml-2 p-1 border border-gray-300 rounded bg-white"
                    >
                      <option value="4">4 bytes</option>
                      <option value="8">8 bytes</option>
                    </select>
                  </div>
                </div>

                <div className="grid md:grid-cols-2 gap-4">
                  <div className="bg-white p-3 rounded border border-gray-200">
                    <h5 className="font-semibold text-sm mb-2">Page Table</h5>
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="bg-gray-100">
                          <th className="p-1 text-left">Page</th>
                          <th className="p-1 text-left">Frame</th>
                        </tr>
                      </thead>
                      <tbody>
                        {pageTable.map((f, i) => (
                          <tr key={i} className={page === i ? 'bg-gray-200' : ''}>
                            <td className="p-1">{i}</td>
                            <td className="p-1">{f}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  <div className="bg-white p-3 rounded border border-gray-200">
                    <h5 className="font-semibold text-sm mb-2">Step-by-Step Translation</h5>
                    <div className="text-sm space-y-1 font-mono text-xs">
                      <p>Logical Address = <strong>{logicalAddress}</strong></p>
                      <p>Page Size = <strong>{pageSize}</strong> bytes</p>
                      <p>Page Number = {logicalAddress} / {pageSize} = <strong>{page}</strong></p>
                      <p>Offset = {logicalAddress} % {pageSize} = <strong>{offset}</strong></p>
                      <p>Frame (from PT) = <strong>{frame}</strong></p>
                      <p className="text-gray-700 font-semibold mt-2">
                        Physical = {frame} x {pageSize} + {offset} = {physicalAddress}
                      </p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="bg-gray-50 p-5 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-4">Page Table Variants</h4>
              <div className="space-y-4">
                <div className="bg-white p-4 rounded border-l-4 border-gray-400">
                  <h5 className="font-semibold text-gray-900">Hierarchical Paging (Multi-level Page Tables)</h5>
                  <p className="text-sm text-gray-700 mt-2">
                    Break the page table into smaller pieces. A two-level scheme uses an outer page table 
                    to point to inner page tables. This saves memory because unused regions don't need 
                    inner page tables allocated.
                  </p>
                  <div className="bg-slate-900 p-3 rounded mt-2 text-gray-300 text-xs font-mono">
{`// 32-bit address with two-level paging
// Page size = 4KB (12 bits), PT entry = 4 bytes
// Each inner page table fits in one page: 4KB/4B = 1024 entries
// Outer page table: 1024 entries
// Total inner tables: 1024, but only allocated on demand

Logical Address:
| 10 bits (outer) | 10 bits (inner) | 12 bits (offset) |
        p1              p2                d

Translation:
outer_table[p1] -> inner_table_base
inner_table[p2] -> frame_number
physical = frame_number * 4096 + d`}
                  </div>
                </div>

                <div className="bg-white p-4 rounded border-l-4 border-gray-400">
                  <h5 className="font-semibold text-gray-900">Hashed Page Tables</h5>
                  <p className="text-sm text-gray-700 mt-2">
                    Common in address spaces larger than 32 bits (e.g., 64-bit systems). 
                    The page number is hashed into a hash table. Each entry contains a linked list 
                    of elements that hash to the same location to handle collisions.
                  </p>
                  <div className="bg-slate-900 p-3 rounded mt-2 text-gray-300 text-xs font-mono">
{`// Hashed page table structure
struct hash_entry {
    unsigned long page_number;
    unsigned long frame_number;
    struct hash_entry *next;  // collision chain
    unsigned protection_bits;
};

// Average lookup: O(1 + alpha) where alpha = load factor
// With chaining, typically 1-2 comparisons`}
                  </div>
                </div>

                <div className="bg-white p-4 rounded border-l-4 border-gray-400">
                  <h5 className="font-semibold text-gray-900">Inverted Page Tables</h5>
                  <p className="text-sm text-gray-700 mt-2">
                    Instead of one page table per process, there is one global page table with one entry 
                    per physical frame. Each entry stores (process_id, page_number). 
                    Saves enormous memory but lookup is slower (requires search or hashing).
                  </p>
                  <div className="bg-slate-900 p-3 rounded mt-2 text-gray-300 text-xs font-mono">
{`// Memory comparison for 4GB RAM, 4KB pages
Traditional PT per process: 1M entries x 4B = 4MB per process
Inverted PT: 1M frames x 8B = 8MB total for ALL processes

// For 100 processes:
// Traditional: 400MB of page tables!
// Inverted: 8MB regardless of process count`}
                  </div>
                </div>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-slate-900 p-4 rounded-lg">
                <h4 className="text-gray-400 text-sm mb-2">C Code: Simulating Page Table Lookup</h4>
                <pre className="text-gray-300 text-xs font-mono">
{`#include <stdio.h>
#include <stdint.h>

#define PAGE_SIZE 4096
#define NUM_PAGES 1024

uint32_t page_table[NUM_PAGES];

uint32_t translate(uint32_t logical_addr) {
    uint32_t page_num = logical_addr / PAGE_SIZE;
    uint32_t offset = logical_addr % PAGE_SIZE;
    
    uint32_t frame = page_table[page_num];
    uint32_t physical = frame * PAGE_SIZE + offset;
    
    printf("VA=%u -> page=%u, offset=%u, "
           "frame=%u, PA=%u\\n",
           logical_addr, page_num, offset,
           frame, physical);
    
    return physical;
}

int main() {
    // Initialize page table
    page_table[0] = 5;
    page_table[1] = 2;
    page_table[2] = 8;
    
    translate(0);      // -> frame 5
    translate(4096);   // -> frame 2
    translate(8192);   // -> frame 8
    translate(5000);   // page 1, offset 904
    
    return 0;
}`}
                </pre>
              </div>
              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-2">Memory Overhead Analysis</h4>
                <p className="text-sm text-gray-700 mb-3">
                  Paging introduces internal fragmentation. On average, half a page is wasted per process 
                  because the last page is rarely completely full.
                </p>
                <div className="bg-white p-3 rounded border-l-4 border-gray-400">
                  <p className="text-sm font-semibold text-gray-700">Waste Formula</p>
                  <p className="text-xs text-gray-600 mt-1 font-mono">
                    avg_internal_fragmentation = page_size / 2
                  </p>
                  <p className="text-xs text-gray-600 mt-1">
                    For 4KB pages: ~2KB wasted per process on average.
                    For 1,000 processes: ~2MB total waste.
                  </p>
                </div>
                <p className="text-xs text-gray-600 mt-3">
                  However, paging completely eliminates external fragmentation, which is the primary 
                  reason it replaced contiguous allocation in modern systems.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* TLB Deep Dive */}
      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Search className="w-6 h-6 text-gray-500" />
              Translation Lookaside Buffer (TLB)
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <p className="text-gray-700">
              The TLB is a small, fast associative memory cache that stores recent page table entries. 
              Without a TLB, every data/instruction access would require two memory accesses: 
              one for the page table and one for the actual data.
            </p>

            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">TLB Hit Path</h4>
                <ol className="text-sm text-gray-700 space-y-2">
                  <li>1. CPU generates logical address (page, offset)</li>
                  <li>2. Page number is presented to TLB simultaneously</li>
                  <li>3. TLB contains the mapping (hit!)</li>
                  <li>4. Frame number retrieved in ~1 CPU cycle</li>
                  <li>5. Physical address formed and memory accessed</li>
                </ol>
                <div className="bg-white p-3 rounded border-l-4 border-gray-400 mt-3">
                  <p className="text-sm font-semibold text-gray-700">Effective Access Time (Hit)</p>
                  <p className="text-xs text-gray-600 mt-1 font-mono">
                    EAT_hit = TLB_access_time + memory_access_time
                  </p>
                </div>
              </div>

              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">TLB Miss Path</h4>
                <ol className="text-sm text-gray-700 space-y-2">
                  <li>1. CPU generates logical address (page, offset)</li>
                  <li>2. TLB lookup fails (miss)</li>
                  <li>3. Access page table in main memory</li>
                  <li>4. Extract frame number from page table entry</li>
                  <li>5. Update TLB with new entry (may evict old one)</li>
                  <li>6. Access physical memory for data</li>
                </ol>
                <div className="bg-white p-3 rounded border-l-4 border-gray-400 mt-3">
                  <p className="text-sm font-semibold text-gray-700">Effective Access Time (Miss)</p>
                  <p className="text-xs text-gray-600 mt-1 font-mono">
                    EAT_miss = TLB_access_time + 2 * memory_access_time
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-slate-100 p-5 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-3">Effective Access Time Formula</h4>
              <p className="text-sm text-gray-700 mb-3">
                Let h be the TLB hit ratio, t_tlb be TLB access time, and t_mem be memory access time.
              </p>
              <div className="bg-white p-4 rounded border border-gray-300 text-center">
                <p className="text-lg font-mono text-gray-800">
                  EAT = h * (t_tlb + t_mem) + (1 - h) * (t_tlb + 2 * t_mem)
                </p>
                <p className="text-sm text-gray-600 mt-2">
                  Simplified: EAT = t_tlb + t_mem + (1 - h) * t_mem
                </p>
              </div>
              <div className="grid md:grid-cols-2 gap-4 mt-4">
                <div className="bg-white p-3 rounded">
                  <p className="text-sm font-semibold text-gray-700">Example 1: h = 80%</p>
                  <p className="text-xs text-gray-600 mt-1 font-mono">
                    t_tlb = 10ns, t_mem = 100ns
                    <br />
                    EAT = 0.8 * 110 + 0.2 * 210 = 88 + 42 = 130ns
                  </p>
                </div>
                <div className="bg-white p-3 rounded">
                  <p className="text-sm font-semibold text-gray-700">Example 2: h = 98%</p>
                  <p className="text-xs text-gray-600 mt-1 font-mono">
                    t_tlb = 10ns, t_mem = 100ns
                    <br />
                    EAT = 0.98 * 110 + 0.02 * 210 = 107.8 + 4.2 = 112ns
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-slate-900 p-5 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">TLB Hardware Architecture</h4>
              <pre className="text-gray-300 text-xs md:text-sm font-mono">
{`
CPU generates logical address
         |
         v
    +---------+
    | Page #  |-------> TLB (associative memory)
    | Offset  |             |
    +---------+             | Hit
         |                  v
         |             +----------+
         |             | Frame #  |
         |             +----------+
         |                  |
         | Miss             v
         |             Physical Address
         v                  |
    Page Table in           v
    Main Memory      Data Access to RAM
         |
         v
    Update TLB
`}
              </pre>
            </div>

            <div className="bg-gray-50 p-5 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-3">TLB Characteristics</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-slate-200">
                      <th className="p-3 text-left">Property</th>
                      <th className="p-3 text-left">Typical Value</th>
                      <th className="p-3 text-left">Impact</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Size</td>
                      <td className="p-3">32-4096 entries</td>
                      <td className="p-3">Larger = better hit rate but slower access</td>
                    </tr>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Access Time</td>
                      <td className="p-3">0.5-2 CPU cycles (~1-10ns)</td>
                      <td className="p-3">Much faster than main memory</td>
                    </tr>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Hit Ratio</td>
                      <td className="p-3">80-99%+</td>
                      <td className="p-3">Depends on working set size</td>
                    </tr>
                    <tr className="bg-white">
                      <td className="p-3 font-medium">Associativity</td>
                      <td className="p-3">4-way to fully associative</td>
                      <td className="p-3">Higher = fewer conflicts</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Protection and Sharing */}
      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="w-6 h-6 text-gray-500" />
              Protection and Sharing in Paging
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Protection Bits</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Each page table entry contains protection bits that control access to the page.
                </p>
                <ul className="text-sm text-gray-700 space-y-1">
                  <li><strong>Valid-Invalid Bit:</strong> Page is in memory (valid) or not (invalid)</li>
                  <li><strong>Read/Write Bit:</strong> Page is read-only or writable</li>
                  <li><strong>Execute Bit:</strong> Code can be executed from this page</li>
                  <li><strong>User/Supervisor Bit:</strong> Access restricted to kernel mode</li>
                </ul>
                <div className="bg-slate-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`// Page Table Entry (typical x86)
| Frame Number (20 bits) | Flags (12 bits) |

Flags:
  P  - Present (valid/invalid)
  R/W - Read/Write
  U/S - User/Supervisor
  XD  - Execute Disable (NX bit)
  A   - Accessed
  D   - Dirty`}
                </div>
              </div>

              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Shared Pages</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Multiple processes can share the same physical frame by mapping it to different 
                  logical pages in their respective page tables.
                </p>
                <ul className="text-sm text-gray-700 space-y-1">
                  <li><strong>Shared Libraries:</strong> libc, system DLLs</li>
                  <li><strong>Shared Memory IPC:</strong> shmget, mmap</li>
                  <li><strong>Read-Only Code:</strong> Text segments of programs</li>
                </ul>
                <div className="bg-slate-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`// Process A page table    Process B page table
Page 2 -> Frame 10        Page 5 -> Frame 10
(read-only shared)        (read-only shared)

Both processes access the SAME
physical memory containing libc.so`}
                </div>
              </div>
            </div>

            <div className="bg-slate-900 p-5 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">Copy-on-Write (COW) Mechanism</h4>
              <pre className="text-gray-300 text-xs md:text-sm font-mono">
{`
Process A forks Process B:

Initial state (after fork):
  Process A              Process B
  Page 0 -> Frame 5      Page 0 -> Frame 5  (shared, read-only)
  Page 1 -> Frame 3      Page 1 -> Frame 3  (shared, read-only)
       Both point to same frames, marked read-only

When Process B writes to Page 1:
  1. MMU detects write to read-only page
  2. Page fault trap to OS
  3. OS allocates new frame (Frame 7)
  4. OS copies contents of Frame 3 to Frame 7
  5. OS updates Process B: Page 1 -> Frame 7 (read-write)
  6. OS resumes Process B on the write instruction

Result:
  Process A              Process B
  Page 0 -> Frame 5      Page 0 -> Frame 5  (still shared)
  Page 1 -> Frame 3      Page 1 -> Frame 7  (private copy)
`}
              </pre>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Segmentation */}
      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Layers className="w-6 h-6 text-gray-500" />
              Segmentation and Segmented Paging
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <p className="text-gray-700">
              Segmentation is a memory-management scheme that supports the user view of memory: 
              a collection of variable-sized segments with no particular ordering. 
              Each segment has a name and a length.
            </p>

            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Segment Table</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Each entry in the segment table contains:
                </p>
                <ul className="text-sm text-gray-700 space-y-1">
                  <li><strong>Base:</strong> Starting physical address of the segment</li>
                  <li><strong>Limit:</strong> Length of the segment in bytes</li>
                  <li><strong>Protection:</strong> Read/Write/Execute permissions</li>
                </ul>
                <div className="bg-slate-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`// Logical address in segmentation
| Segment Number (s) | Offset (d) |
        16 bits           16 bits

// Address translation
if (d >= limit[s]) {
    trap(segmentation fault);
}
physical_address = base[s] + d;`}
                </div>
              </div>

              <div className="bg-gray-50 p-5 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">Typical Program Segments</h4>
                <div className="space-y-2">
                  <div className="bg-white p-3 rounded border-l-4 border-gray-400">
                    <p className="text-sm font-semibold text-gray-700">Code Segment (.text)</p>
                    <p className="text-xs text-gray-600">Program instructions. Read-only, executable.</p>
                  </div>
                  <div className="bg-white p-3 rounded border-l-4 border-gray-400">
                    <p className="text-sm font-semibold text-gray-700">Data Segment (.data, .bss)</p>
                    <p className="text-xs text-gray-600">Global and static variables. Read-write.</p>
                  </div>
                  <div className="bg-white p-3 rounded border-l-4 border-gray-400">
                    <p className="text-sm font-semibold text-gray-700">Heap Segment</p>
                    <p className="text-xs text-gray-600">Dynamically allocated memory. Grows upward.</p>
                  </div>
                  <div className="bg-white p-3 rounded border-l-4 border-gray-400">
                    <p className="text-sm font-semibold text-gray-700">Stack Segment</p>
                    <p className="text-xs text-gray-600">Local variables, return addresses. Grows downward.</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-slate-900 p-5 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">Segmentation Address Translation</h4>
              <pre className="text-gray-300 text-xs md:text-sm font-mono">
{`
Logical Address: (Segment=1, Offset=100)
         |
         v
    +------------+
    | Segment    |----> Segment Table
    | Number (1) |      +------------------+
    +------------+      | Seg 0: base=1000 |
         |              |        limit=500 |
         v              | Seg 1: base=5000 |
    +------------+      |        limit=800 |
    | Offset     |      | Seg 2: base=9000 |
    | (100)      |      |        limit=300 |
    +------------+      +------------------+
         |                     |
         v                     v
    Check: 100 < 800?   ->   base[1] = 5000
         YES                    +
         |                   offset = 100
         v                       |
    Physical Address = 5100 <----+
`}
              </pre>
            </div>

            <div className="bg-gray-50 p-5 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-4">Paging vs Segmentation Comparison</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-slate-200">
                      <th className="p-3 text-left">Aspect</th>
                      <th className="p-3 text-left">Paging</th>
                      <th className="p-3 text-left">Segmentation</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Unit Size</td>
                      <td className="p-3">Fixed-size pages</td>
                      <td className="p-3">Variable-size segments</td>
                    </tr>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Fragmentation</td>
                      <td className="p-3">Internal fragmentation only</td>
                      <td className="p-3">External fragmentation</td>
                    </tr>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Program Structure</td>
                      <td className="p-3">Invisible to programmer</td>
                      <td className="p-3">Visible (code, data, stack)</td>
                    </tr>
                    <tr className="border-b bg-white">
                      <td className="p-3 font-medium">Sharing</td>
                      <td className="p-3">Page-level sharing</td>
                      <td className="p-3">Segment-level sharing</td>
                    </tr>
                    <tr className="bg-white">
                      <td className="p-3 font-medium">Protection</td>
                      <td className="p-3">Per-page protection</td>
                      <td className="p-3">Per-segment protection (natural)</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="bg-slate-100 p-5 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-3">Segmentation with Paging: Intel x86 Architecture</h4>
              <p className="text-sm text-gray-700 mb-3">
                Modern x86 processors combine segmentation and paging. Each segment is divided into pages. 
                This gives the benefits of both: logical program structure from segmentation and 
                elimination of external fragmentation from paging.
              </p>
              <div className="bg-slate-900 p-4 rounded text-gray-300 text-xs font-mono">
{`// Intel x86 logical to physical translation
// Step 1: Segmentation
logical_address -> segment_selector:offset
segment_table -> segment_base + offset = linear_address

// Step 2: Paging (can be disabled)
linear_address -> page_directory:page_table:offset
page_tables -> frame_number
frame_number * page_size + offset = physical_address

// Modern Linux on x86:
// Segmentation is mostly disabled (flat model)
// linear_address == logical_address
// Only paging is actively used`}
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Real World Backend Applications */}
      <motion.div {...fadeIn}>
        <Card className="bg-gray-900 text-white">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <Terminal className="w-6 h-6 text-gray-400" />
              Real-World Backend Engineering Applications
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-slate-700 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-400 mb-2">Linux Huge Pages</h4>
                <p className="text-sm text-gray-300 mb-2">
                  Standard page size is 4KB. For databases and applications with large memory footprints, 
                  Linux supports huge pages (2MB, 1GB) to reduce TLB misses.
                </p>
                <code className="block p-2 bg-slate-900 rounded text-gray-300 text-xs">
{`# Check current huge page settings
cat /proc/meminfo | grep Huge

# Allocate 100 2MB huge pages
sudo sysctl -w vm.nr_hugepages=100

# Use huge pages in Java
java -XX:+UseLargePages -jar app.jar

# Use transparent huge pages (THP)
cat /sys/kernel/mm/transparent_hugepage/enabled

# PostgreSQL huge pages config
huge_pages = try
shared_buffers = 16GB`}
                </code>
                <p className="text-xs text-gray-500 mt-2">
                  <strong>Impact:</strong> Databases like PostgreSQL and MySQL can see 5-15% performance 
                  improvement with huge pages due to fewer TLB misses.
                </p>
              </div>

              <div className="bg-slate-700 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-400 mb-2">Memory Mapping with mmap()</h4>
                <p className="text-sm text-gray-300 mb-2">
                  mmap() maps files directly into the process address space, avoiding read()/write() syscalls 
                  and enabling the OS to manage file caching through the page cache.
                </p>
                <code className="block p-2 bg-slate-900 rounded text-gray-300 text-xs">
{`// C example: memory-mapped file
#include <sys/mman.h>
#include <fcntl.h>

int fd = open("data.bin", O_RDONLY);
size_t size = lseek(fd, 0, SEEK_END);

// Map file into address space
char *addr = mmap(NULL, size, PROT_READ,
                   MAP_PRIVATE, fd, 0);

// Access as memory - no read() syscalls
char first_byte = addr[0];

// Cleanup
munmap(addr, size);
close(fd);`}
                </code>
                <p className="text-xs text-gray-500 mt-2">
                  <strong>Use cases:</strong> Databases (LevelDB, RocksDB), search engines (Elasticsearch), 
                  and large file processing.
                </p>
              </div>

              <div className="bg-slate-700 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-400 mb-2">Inspecting Linux Page Tables</h4>
                <p className="text-sm text-gray-300 mb-2">
                  You can inspect how the kernel maps memory for a process using /proc and pagemap.
                </p>
                <code className="block p-2 bg-slate-900 rounded text-gray-300 text-xs">
{`# View memory mappings of a process
cat /proc/$(pidof myapp)/maps

# Example output:
55c3d8a6b000-55c3d8a8c000 r-xp 00000000 08:01 1310734 /usr/bin/myapp
55c3d8c8b000-55c3d8c8d000 rw-p 00020000 08:01 1310734 /usr/bin/myapp
55c3da4a5000-55c3da4c6000 rw-p 00000000 00:00 0    [heap]
7f8b3c000000-7f8b3c021000 rw-p 00000000 00:00 0 
7f8b3c021000-7f8b40000000 ---p 00000000 00:00 0 
7ffcb5c5d000-7ffcb5c7e000 rw-p 00000000 00:00 0  [stack]

# Check page size
getconf PAGE_SIZE  # Usually 4096`}
                </code>
              </div>

              <div className="bg-slate-700 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-400 mb-2">Docker Memory Limits</h4>
                <p className="text-sm text-gray-300 mb-2">
                  Docker memory limits work through Linux cgroups, which constrain how much physical 
                  memory a process can use.
                </p>
                <code className="block p-2 bg-slate-900 rounded text-gray-300 text-xs">
{`# Run container with 512MB limit
docker run --memory=512m --memory-swap=512m myapp

# Kubernetes memory limits
resources:
  limits:
    memory: "512Mi"
  requests:
    memory: "256Mi"

# What happens on exceed:
# 1. Container is OOM-killed by kernel
# 2. Docker restarts it (if restart policy set)
# 3. Events logged to dmesg`}
                </code>
                <p className="text-xs text-gray-500 mt-2">
                  <strong>Backend lesson:</strong> Always set memory limits and monitor for OOM kills 
                  in production.
                </p>
              </div>
            </div>

            <div className="bg-slate-700 p-4 rounded-lg">
              <h4 className="font-semibold text-gray-400 mb-2">Performance: Understanding TLB Misses</h4>
              <p className="text-sm text-gray-300 mb-2">
                In high-performance systems, TLB misses can dominate latency. Tools like perf can measure them.
              </p>
              <code className="block p-2 bg-slate-900 rounded text-gray-300 text-xs">
{`# Count TLB misses for a program
perf stat -e dTLB-loads,dTLB-load-misses,iTLB-load-misses ./myapp

# Example output:
 Performance counter stats for './myapp':
     1,234,567,890      dTLB-loads
        45,678,901      dTLB-load-misses     (3.7%)
         1,234,567      iTLB-load-misses

# High miss rate? Solutions:
# 1. Use huge pages
# 2. Improve data locality
# 3. Reduce working set size
# 4. Use cache-friendly data structures`}
              </code>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Cpu className="w-6 h-6 text-gray-500" />
              Advanced Memory Architecture
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-2">NUMA Architecture and Memory Affinity</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Non-Uniform Memory Access (NUMA) systems have multiple memory controllers, each local to a CPU socket. Accessing local memory is faster than remote memory. Linux exposes NUMA topology via <code>/sys/devices/system/node</code>.
                </p>
                <p className="text-sm text-gray-700">
                  The kernel's NUMA balancer migrates pages toward the CPUs that access them most. Users can pin memory and threads with <code>numactl</code>. First-touch allocation policy places pages on the NUMA node of the accessing CPU.
                </p>
                <div className="bg-gray-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`# Show NUMA topology
numactl --hardware

# Bind process to node 0 memory and CPUs
numactl --cpunodebind=0 --membind=0 ./app

# Interleave memory across all nodes
numactl --interleave=all ./app

# Check NUMA page distribution
numastat -p $(pidof myapp)`}
                </div>
              </div>

              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-2">Huge Pages and Transparent HugePages (THP)</h4>
                <p className="text-sm text-gray-700 mb-2">
                  Standard x86 pages are 4KB. Huge pages use 2MB or 1GB frames, reducing TLB pressure by 512x or 262,144x. This is critical for databases with multi-GB resident sets.
                </p>
                <p className="text-sm text-gray-700">
                  <strong>Transparent HugePages (THP)</strong> automatically coalesces contiguous 4KB pages into 2MB pages in the background. It can be enabled globally or only for applications that explicitly request it via <code>madvise</code>.
                </p>
                <div className="bg-gray-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`# Allocate 100 2MB huge pages at boot
echo 100 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

# THP settings
cat /sys/kernel/mm/transparent_hugepage/enabled
# always / madvise / never

# Use madvise for THP in application
madvise(addr, length, MADV_HUGEPAGE);`}
                </div>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <h4 className="font-semibold text-gray-900 mb-3">Cache Coherency and Page Coloring</h4>
              <p className="text-sm text-gray-700 mb-3">
                Multi-core CPUs maintain cache coherency using protocols like MESI and MOESI. Understanding cache line states is essential for lock-free programming and false-sharing avoidance.
              </p>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="p-2 text-left">State</th>
                      <th className="p-2 text-left">Meaning (MESI)</th>
                      <th className="p-2 text-left">Meaning (MOESI)</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b"><td className="p-2 font-medium">M</td><td className="p-2">Modified (exclusive, dirty)</td><td className="p-2">Modified (exclusive, dirty)</td></tr>
                    <tr className="border-b"><td className="p-2 font-medium">E</td><td className="p-2">Exclusive (clean)</td><td className="p-2">Exclusive (clean)</td></tr>
                    <tr className="border-b"><td className="p-2 font-medium">S</td><td className="p-2">Shared (clean, read-only)</td><td className="p-2">Shared (clean, read-only)</td></tr>
                    <tr className="border-b"><td className="p-2 font-medium">I</td><td className="p-2">Invalid</td><td className="p-2">Invalid</td></tr>
                    <tr className="border-b"><td className="p-2 font-medium">O</td><td className="p-2">N/A</td><td className="p-2">Owned (dirty, shared) - source for forward</td></tr>
                  </tbody>
                </table>
              </div>
              <p className="text-sm text-gray-700 mt-3">
                <strong>Page coloring</strong> is an OS technique to control which cache sets physical pages map to. By restricting allocation to specific "colors," the OS can prevent cache conflicts and improve deterministic performance in real-time systems.
              </p>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div {...fadeIn}>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <MemoryStick className="w-6 h-6 text-gray-500" />
              Kernel Memory Subsystems
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-2">Slab Allocators and Object Caches</h4>
                <p className="text-sm text-gray-700 mb-2">
                  The Linux kernel uses the SLUB allocator (successor to SLAB) to manage small, frequently allocated objects. Each object type (e.g., <code>task_struct</code>, <code>inode</code>, <code>dentry</code>) has a dedicated kmem_cache.
                </p>
                <p className="text-sm text-gray-700">
                  SLUB eliminates internal fragmentation for kernel objects and provides fast allocation via per-CPU partial lists. It also detects use-after-free bugs via REDZONE padding and poisoning.
                </p>
                <div className="bg-gray-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`# Inspect slab caches
cat /proc/slabinfo
slabtop

# Example high-traffic caches:
# dentry, inode_cache, kmalloc-*, task_struct

# kmemleak for memory leak detection
CONFIG_DEBUG_KMEMLEAK=y`}
                </div>
              </div>

              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-2">Kernel Same-page Merging (KSM)</h4>
                <p className="text-sm text-gray-700 mb-2">
                  KSM is a memory deduplication mechanism. The kernel scans user pages for identical content and merges them into a single write-protected page. If a process writes to a shared KSM page, a copy is made (COW).
                </p>
                <p className="text-sm text-gray-700">
                  KSM is heavily used in virtualization (KVM) and containers where many VMs run identical operating systems. It trades CPU cycles for memory density.
                </p>
                <div className="bg-gray-900 p-3 rounded mt-3 text-gray-300 text-xs font-mono">
{`# Enable KSM
echo 1 > /sys/kernel/mm/ksm/run

# Tune scanning aggressiveness
echo 1000 > /sys/kernel/mm/ksm/pages_to_scan
echo 200 > /sys/kernel/mm/ksm/sleep_millisecs

# Check savings
cat /sys/kernel/mm/ksm/pages_sharing`}
                </div>
              </div>
            </div>

            <div className="bg-gray-900 p-4 rounded-lg overflow-x-auto">
              <h4 className="text-gray-400 text-sm mb-3">Memory Bandwidth and Contention</h4>
              <pre className="text-gray-300 text-xs font-mono">
{`
Single-socket bandwidth: ~200-300 GB/s (DDR5)
Remote NUMA bandwidth:   ~100-150 GB/s (via UPI/Infinity Fabric)

Memory-bound application optimization:
1. Use local NUMA nodes (numactl --membind)
2. Reduce cache line bouncing (pad shared data to 64B)
3. Use huge pages to lower page-table walk overhead
4. Enable hardware prefetchers in BIOS
5. For HPC: consider Page Coloring to prevent cache thrashing
`}
              </pre>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Key Takeaways */}
      <motion.div {...fadeIn}>
        <Card className="bg-gray-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CheckCircle className="w-6 h-6 text-gray-500" />
              Key Takeaways
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {[
                "The MMU translates logical addresses to physical addresses using base/limit registers or page tables",
                "Contiguous allocation suffers from external fragmentation; paging eliminates it at the cost of internal fragmentation",
                "First fit is fastest in practice, best fit leaves tiny fragments, worst fit leaves larger pieces",
                "A logical address is divided into (page number, offset); the page table maps pages to frames",
                "The TLB caches page table entries; EAT = h*(t_tlb + t_mem) + (1-h)*(t_tlb + 2*t_mem)",
                "Hierarchical paging, hashed page tables, and inverted page tables solve large page table problems",
                "Segmentation matches program structure but suffers from external fragmentation; x86 combines both segmentation and paging",
                "Real-world optimizations include huge pages (reduce TLB misses), mmap (fast file I/O), and cgroup memory limits"
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-gray-500 text-white flex items-center justify-center text-sm font-semibold">
                    {i + 1}
                  </span>
                  <span className="text-gray-700">{item}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
}
